If token doesn't exist, don't throw typeError
Fixes this error:

```
Running "cssmin:target" (cssmin) task
[D] Task source: C:\Users\Philip\Dropbox\GitHub\bd-tracker-amphibiaweb\node_modules\grunt-contrib-cssmin\tasks\cssmin.js
Verifying property cssmin.target exists in config...OK
Files: css/main.css -> css/main.min.css
Options: rebase=false, report="min", sourceMap, advanced=false
>> TypeError: token[0][0].indexOf is not a function
Warning: CSS minification failed at css/main.css. Use --force to continue.
```